import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500"
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`${poppins.className} container h-screen w-screen flex flex-nowrap gap-10 items-start p-10`}>
          <div className="border-[1.4px] border-slate-900 w-[300px] h-auto rounded-md">
            <h1 className="bg-slate-500 p-4 text-white rounded-t-md">All Routes</h1>
            <ul className="ps-4 my-4 text-[13px] font-semibold flex flex-col items-start gap-3 text-slate-600">
              <li>1. <Link href="/">Home</Link></li>
              <li>2. <Link href="/frontend/users">GET</Link></li>
              <li>3. <Link href="/frontend/addusers">POST</Link></li>
              <li>4. <Link href="/frontend/users/:id">PUT</Link></li>
              <li>5. <Link href="google">DELETE</Link></li>
              <li>6. <Link href="/frontend/upload">Upload Image</Link></li>
            </ul>
          </div>

          <div className="">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
